apiVersion: v1
kind: Service
metadata:
  name: rishabhp2899@gamil.com-service
spec:
  selector:
    app: rishabhp2899@gamil.com
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
